# remote_theme: sujaykundu777/devlopr-jekyll  # Don't touch ( required for this theme)

# Edit your preferences below 
title: Robin Rumpunen
subtitle: Prop Artist and Game Engine Enthusiast
description: >- # this means to ignore newlines until "baseurl:"
  John Doe uses devlopr-jekyll - a Jekyll Theme Built For Developers

url: "https://robinrumpunen.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    # - text: Blog
      # url: /blog
    - text: About
      url: /about
    - text: Engine
      url: /engine
    - text: Art
      url : https://robinr.artstation.com/projects

# Edit these details 

author_logo: profile.png
author: Robin Rumpunen
author_bio: Hi, my name is Robin Rumpunen, swedish artist and programmer from Halland. </p><p>Uncovering the mysteries of days past is my motto.</p>
author_email: ""
author_location: Sweden, Malmö
author_website_url: "https://robinrumpunen.github.io"

author_work_experiences: 
            - company_name: " Prop Artist &emsp; &emsp; &ensp; 2019/04/01 - present <br>
              Junior Prop Artist  2017/07/03 - 2019/03/31 "
              company_logo: MassiveEnt.png
              company_url: https://massive.se
              designation: Massive Entertainment
              description: Prop Artist working on The Division 2.
              visibility: true
            - company_name: Massive Entertainment
              company_logo: MassiveEnt.png
              company_url: https://massive.com
              designation: Junior Prop Artist
              description: Junior Prop Artist on The Division 2.
              visibility: false

author_project_details:
              - project_thumbnail: EchoEngine.png
                project_title: Echo Engine
                project_description: A personal Game Engine.
                project_url: https://robinrumpunen.github.io/engine
                visibility: true
              - project_thumbnail: programmingebooks.png
                project_title: Programming Ebooks
                project_description: A Platform to easily find and read programming books
                project_url: https://programmingebooks.com
                visibility: false

author_education_details:
              - college_logo: mit.png
                college_name: MIT
                college_url: https://mit.org
                college_degree: CS Engineer
                description: Bachelor of Technology
                visibility: true

# social links
twitter_username: robin_rrrr
github_username:  robinrumpunen
facebook_username: 
linkedin_username: robin-rumpunen-b7bb55140/
behance_username: helloRobinRumpunen@gmail.com
instagram_username: 
medium_username: 
dribbble_username: 
flickr_username:  
artstation_username: robinr
formspree_email: robinrumpunenContact@gmail.com

# google analytics
google_analytics: UA-147350173-1 

#for comments using disqus
  # disqus_shortname: sujay-kundu

# wakatime username
  # wakatime_username: sujaykundu777

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_project_details: true
show_author_education_details: false

# dont touch this unless required
# plugins:
#   - jekyll-paginate
#   - jekyll-gist
#   - jekyll-seo-tag
#   - jekyll-sitemap
#   - jekyll-feed

  # - jekyll-remote-theme
  # - jekyll-archives

# pagination of posts
paginate: 8
per_page: 4
paginate_path: "/blog/page/:num/"

# minify 
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'


